version: '3'  
services:  
  main:
    image: mysite:1.0.0
    build:
      context: ..
      dockerfile: Dockerfile
    ports:  
      - "8000:8000"  
    volumes:  
      - ../mysite:/usr/src/app/mysite
